#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TimeOfDeath.Droid.Resource", IsApplication=true)]

namespace TimeOfDeath.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int condition = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int inair = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int inwater = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int outwater = 2131034115;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int crucifix_colour = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int crucifix_grey = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int ic_tab_conditions = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_tab_dead = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_tab_weather = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int tod_colour = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int tod_grey = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int weather_colour = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int weather_grey = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int bodyCondSpinner = 2131099650;
			
			// aapt resource value: 0x7f060009
			public const int calculateButton = 2131099657;
			
			// aapt resource value: 0x7f06000c
			public const int dateLabel = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int editDate = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int editTime = 2131099664;
			
			// aapt resource value: 0x7f060004
			public const int foundAirSpinner = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int foundWaterSpinner = 2131099654;
			
			// aapt resource value: 0x7f06001b
			public const int frameLayout1 = 2131099675;
			
			// aapt resource value: 0x7f060008
			public const int fromWaterSpinner = 2131099656;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int linearLayout2 = 2131099659;
			
			// aapt resource value: 0x7f06000e
			public const int linearLayout3 = 2131099662;
			
			// aapt resource value: 0x7f060011
			public const int linearLayout4 = 2131099665;
			
			// aapt resource value: 0x7f060014
			public const int linearLayout5 = 2131099668;
			
			// aapt resource value: 0x7f060017
			public const int linearLayout6 = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int tempBody = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int tempBodyLabel = 2131099666;
			
			// aapt resource value: 0x7f060016
			public const int tempSurround = 2131099670;
			
			// aapt resource value: 0x7f060015
			public const int tempSurroundLabel = 2131099669;
			
			// aapt resource value: 0x7f06000f
			public const int timeFoundLabel = 2131099663;
			
			// aapt resource value: 0x7f060019
			public const int weightBody = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int weightBodyKG = 2131099674;
			
			// aapt resource value: 0x7f060018
			public const int weightLabel = 2131099672;
			
			// aapt resource value: 0x7f060000
			public const int widget42 = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int widget43 = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int widget45 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int widget47 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int widget49 = 2131099655;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int conditions = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int founddetails = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Close = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Copyright = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int bodyCondition = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int calcTOD = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int clearData = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int date = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int dateFound = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int deathon = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int foundAir = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int foundWater = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int fromWater = 2130968594;
			
			// aapt resource value: 0x7f04000c
			public const int hours = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int inkilo = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int tempBody = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int tempSurround = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int timeFound = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int unknown = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int weightBody = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
