#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidTimeOfDeath.Resource", IsApplication=true)]

namespace AndroidTimeOfDeath
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int condition = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int inair = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int inwater = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int outwater = 2131034115;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int close = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int crucifix_colour = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int crucifix_grey = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int exclaim = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int forensicscience = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_tab_conditions = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_tab_dead = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_tab_weather = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int tod = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int tod_colour = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int tod_grey = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int tod_large = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int weather_colour = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int weather_grey = 2130837517;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07000a
			public const int ScrollView01 = 2131165194;
			
			// aapt resource value: 0x7f070018
			public const int blankLine = 2131165208;
			
			// aapt resource value: 0x7f070023
			public const int blanks = 2131165219;
			
			// aapt resource value: 0x7f070002
			public const int bodyCondSpinner = 2131165186;
			
			// aapt resource value: 0x7f070009
			public const int calculateButton = 2131165193;
			
			// aapt resource value: 0x7f070035
			public const int close = 2131165237;
			
			// aapt resource value: 0x7f070036
			public const int conditionsTable = 2131165238;
			
			// aapt resource value: 0x7f070010
			public const int dateDisplay = 2131165200;
			
			// aapt resource value: 0x7f07000d
			public const int dateLabel = 2131165197;
			
			// aapt resource value: 0x7f07003b
			public const int dateResults = 2131165243;
			
			// aapt resource value: 0x7f07000c
			public const int dateRowLabel = 2131165196;
			
			// aapt resource value: 0x7f070038
			public const int deathOccuredLabel = 2131165240;
			
			// aapt resource value: 0x7f070034
			public const int email = 2131165236;
			
			// aapt resource value: 0x7f07003d
			public const int filler = 2131165245;
			
			// aapt resource value: 0x7f070012
			public const int fillerLine = 2131165202;
			
			// aapt resource value: 0x7f070004
			public const int foundAirSpinner = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int foundWaterSpinner = 2131165190;
			
			// aapt resource value: 0x7f070008
			public const int fromWaterSpinner = 2131165192;
			
			// aapt resource value: 0x7f070033
			public const int images = 2131165235;
			
			// aapt resource value: 0x7f07000b
			public const int mainLayout = 2131165195;
			
			// aapt resource value: 0x7f070037
			public const int resultsRow1 = 2131165239;
			
			// aapt resource value: 0x7f07003a
			public const int resultsRow2 = 2131165242;
			
			// aapt resource value: 0x7f07003c
			public const int resultsRow3 = 2131165244;
			
			// aapt resource value: 0x7f07003e
			public const int resultsRow4 = 2131165246;
			
			// aapt resource value: 0x7f07000f
			public const int surroundRow = 2131165199;
			
			// aapt resource value: 0x7f070019
			public const int tableLayout1 = 2131165209;
			
			// aapt resource value: 0x7f07001a
			public const int tableRow1 = 2131165210;
			
			// aapt resource value: 0x7f07001d
			public const int tableRow2 = 2131165213;
			
			// aapt resource value: 0x7f070020
			public const int tableRow3 = 2131165216;
			
			// aapt resource value: 0x7f07000e
			public const int tableRow4 = 2131165198;
			
			// aapt resource value: 0x7f070011
			public const int tableRow5 = 2131165201;
			
			// aapt resource value: 0x7f07001c
			public const int tempBody = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int tempBodyLabel = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int tempRow = 2131165207;
			
			// aapt resource value: 0x7f07001f
			public const int tempSurround = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int tempSurroundLabel = 2131165214;
			
			// aapt resource value: 0x7f070016
			public const int timeFound = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int timeFoundLabel = 2131165204;
			
			// aapt resource value: 0x7f070039
			public const int timeResults = 2131165241;
			
			// aapt resource value: 0x7f070015
			public const int timeRow = 2131165205;
			
			// aapt resource value: 0x7f070013
			public const int timeRowLabel = 2131165203;
			
			// aapt resource value: 0x7f070031
			public const int title = 2131165233;
			
			// aapt resource value: 0x7f070022
			public const int weightBody = 2131165218;
			
			// aapt resource value: 0x7f070024
			public const int weightBodyKG = 2131165220;
			
			// aapt resource value: 0x7f070021
			public const int weightLabel = 2131165217;
			
			// aapt resource value: 0x7f070025
			public const int widget0 = 2131165221;
			
			// aapt resource value: 0x7f070032
			public const int widget34 = 2131165234;
			
			// aapt resource value: 0x7f070030
			public const int widget38 = 2131165232;
			
			// aapt resource value: 0x7f070000
			public const int widget42 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int widget43 = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int widget45 = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int widget47 = 2131165189;
			
			// aapt resource value: 0x7f070026
			public const int widget48 = 2131165222;
			
			// aapt resource value: 0x7f070007
			public const int widget49 = 2131165191;
			
			// aapt resource value: 0x7f070027
			public const int widget50 = 2131165223;
			
			// aapt resource value: 0x7f070028
			public const int widget52 = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int widget55 = 2131165225;
			
			// aapt resource value: 0x7f07002a
			public const int widget56 = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int widget57 = 2131165227;
			
			// aapt resource value: 0x7f07002c
			public const int widget58 = 2131165228;
			
			// aapt resource value: 0x7f07002d
			public const int widget59 = 2131165229;
			
			// aapt resource value: 0x7f07002e
			public const int widget60 = 2131165230;
			
			// aapt resource value: 0x7f07002f
			public const int widget61 = 2131165231;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int conditions = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int datepicker = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int datepicker2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int datepicker3 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int information = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int results = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Close = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Copyright = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int bodyCondition = 2130968579;
			
			// aapt resource value: 0x7f04000f
			public const int calcTOD = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int clearData = 2130968590;
			
			// aapt resource value: 0x7f04000d
			public const int date = 2130968589;
			
			// aapt resource value: 0x7f040004
			public const int dateFound = 2130968580;
			
			// aapt resource value: 0x7f04000a
			public const int deathon = 2130968586;
			
			// aapt resource value: 0x7f040010
			public const int foundAir = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int foundWater = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int fromWater = 2130968594;
			
			// aapt resource value: 0x7f04000c
			public const int hours = 2130968588;
			
			// aapt resource value: 0x7f040009
			public const int inkilo = 2130968585;
			
			// aapt resource value: 0x7f040006
			public const int tempBody = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int tempSurround = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int timeFound = 2130968581;
			
			// aapt resource value: 0x7f04000b
			public const int unknown = 2130968587;
			
			// aapt resource value: 0x7f040008
			public const int weightBody = 2130968584;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Splash = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
